2025-05-15 21:58:35,874 - INFO - üü¢ Starting job: job_0010
2025-05-15 21:58:36,092 - ERROR - ‚ùå Error in job job_0010: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
Traceback (most recent call last):
  File "\\mull.sms.ed.ac.uk\home\s1834431\Win7\Desktop\fem_model\workflow_orchestrator\run_job.py", line 128, in process_job
    all_elements = create_elements_batch(mesh_dictionary, params_list)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\mull.sms.ed.ac.uk\home\s1834431\Win7\Desktop\fem_model\pre_processing\element_library\element_factory.py", line 43, in create_elements_batch
    elements = _instantiate_elements(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "\\mull.sms.ed.ac.uk\home\s1834431\Win7\Desktop\fem_model\pre_processing\element_library\element_factory.py", line 81, in _instantiate_elements
    elements = np.vectorize(
               ^^^^^^^^^^^^^
  File "C:\Users\s1834431\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\lib\_function_base_impl.py", line 2522, in __call__
    return self._call_as_normal(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s1834431\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\lib\_function_base_impl.py", line 2515, in _call_as_normal
    return self._vectorize_call(func=func, args=vargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s1834431\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\lib\_function_base_impl.py", line 2605, in _vectorize_call
    outputs = ufunc(*inputs)
              ^^^^^^^^^^^^^^
  File "\\mull.sms.ed.ac.uk\home\s1834431\Win7\Desktop\fem_model\pre_processing\element_library\element_factory.py", line 111, in _safe_instantiate
    element = cls(**params)
              ^^^^^^^^^^^^^
  File "\\mull.sms.ed.ac.uk\home\s1834431\Win7\Desktop\fem_model\pre_processing\element_library\euler_bernoulli\euler_bernoulli_6DOF.py", line 70, in __init__
    self._init_element_geometry()
  File "\\mull.sms.ed.ac.uk\home\s1834431\Win7\Desktop\fem_model\pre_processing\element_library\euler_bernoulli\euler_bernoulli_6DOF.py", line 90, in _init_element_geometry
    conn = self.mesh_dictionary["connectivity"][self.element_id]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
2025-05-15 21:58:36,109 - ERROR - Cleaning up failed job directory: \\mull.sms.ed.ac.uk\home\s1834431\Win7\Desktop\fem_model\post_processing\results\job_0010_2025-05-15_21-58-35
